### ISSUE TITLE
How to Connect to the SSL enabled database ?

### ISSUE THREAD

**Issue by tonywdh** [tmcallaghan/sysbench-mongodb#12]
There is no option for connecting this tool to MongoDb database  if SSL is enabled on the Database. 
Please update the code so that it can support ssl  and  we can put the path of ca cert in the config.bash

**Comment by SethSanchez** [comment]
+1! We're looking to modify this in house. If we can get it working using the 2.x driver, we'll commit upstream.

**Comment by SethSanchez** [comment]
Hey Tony,

It's been a long time for this one, but this is what we ended up adding to the scripts, since we changed quite a few things:

We added the following to the execute and load java files:

```
import com.mongodb.MongoClientURI;


// build connection uri
StringBuilder serverUri = new StringBuilder("mongodb://");
if (!(userName.isEmpty() || userName.equalsIgnoreCase("none"))) {
    serverUri.append(String.format("%s:%s@", userName, passWord));
}
serverUri.append(String.format("%s:%d/%s?ssl=true&authSource=admin", serverName, serverPort, dbName));
MongoClientOptions.Builder clientOptionsBuilder = new MongoClientOptions.Builder().connectionsPerHost(2048).socketTimeout(60000).writeConcern(myWC);
MongoClientURI clientUri = new MongoClientURI(serverUri.toString(), clientOptionsBuilder);
MongoClient m = new MongoClient(clientUri);
```

We replaced the MongoClientOptions and MongoClient lines 158 to 168.

Hope this helps.
